name: ci

on:
  # push:
  #   branches:
  #     - 'main'

  workflow_dispatch:
    inputs:
      site:
        description: "Site"
        default: 'cbss'
        options:
          - 'cbss'
        required: true
        type: choice
      imageTagPrefix:
        description: "Image Tag"
        default: "7.3.0"
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: "cms/Dockerfile"
          push: true
          tags: taha2009/githubactiontest:${{ github.run_number }}
